import { Inter } from "next/font/google";
import "./globals.css";
import AuthSessionProvider from "@/components/Providers/sessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthSessionProvider>
        <body className={inter.className}>{children}</body>
      </AuthSessionProvider>
    </html>
  );
}
